apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-deployment
  labels:
    app: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
      - name: gitea
        image: gitea/gitea:1.20.2
        ports:
        - containerPort: 3000
          name: gitea-http
        - containerPort: 22
          name: gitea-ssh
        env:
        - name: USER_UID
          value: "1000"
        - name: USER_GID
          value: "1000"
        - name: APP_NAME
          value: "SOLXYZ Standard Gitea"
        - name: PROTOCOL
          value: "http"
        - name: GITEA_DOMAIN
          value: "43.206.107.101"
        - name: GITEA__database__DB_TYPE
          value: "postgres"
        - name: GITEA__database__HOST
          value: "postgres-svc:5432"
        - name: GITEA__database__NAME
          value: "gitea"
        - name: GITEA__database__USER
          value: "gitea"
        - name: GITEA__database__PASSWD
          value: "gitea"
        - name: GITEA__webhook__ALLOWED_HOST_LIST
          value: "*"
        volumeMounts:
        - name: gitea-data
          mountPath: "/data"
        - name: timezone
          mountPath: "/etc/timezone"
          readOnly: true
        - name: localtime
          mountPath: "/etc/localtime"
          readOnly: true
      volumes:
      - name: gitea-data
        hostPath:
          path: /var/microk8s/gitea/data
      - name: timezone
        hostPath:
          path: /etc/timezone
      - name: localtime
        hostPath:
          path: /etc/localtime

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
          name: pg-connection
        env:
        - name: POSTGRES_USER
          value: "gitea"
        - name: POSTGRES_PASSWORD
          value: "gitea"
        - name: POSTGRES_DB
          value: "gitea"
        volumeMounts:
        - name: postgres-data
          mountPath: "/var/lib/postgresql/data"
      volumes:
      - name: postgres-data
        hostPath:
          path: /var/microk8s/postgresql/data
---

apiVersion: v1
kind: Service
metadata:
  name: gitea-svc
spec:
  type: NodePort
  selector:
    app: gitea
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: gitea-http
      nodePort: 30000

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: pg-connection
